version: '3.8'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: drupal-app
    container_name: drupal_app
    ports:
      - "5000:80"
    volumes:
      - ./web:/var/www/html/web
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: drupal_db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
