apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files-pvc
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if your storage supports it and you need multiple pods writing
  resources:
    requests:
      storage: 5Gi # Adjust storage size as needed
